### PR TITLE
ADD: Kill Batch

### PR DESCRIPTION
**Pull request by sihrc**

### CODE REVIEW

**Comment by madisonmay** [comment]
In general looks good to me.  Going to go back in, re-add the batch apis + a bunch of deprecation warnings, since I don't think this is a change we should realistically push directly.

**Comment by madisonmay** [comment]
Probably should do the same for PHP.

**Comment by madisonmay** [comment]
Batch is dead, long live batch.

**Comment by madisonmay** [comment]
Quick sanity check for the deprecation warnings @sihrc ?

**Comment by sihrc** [comment]
LGTM

**Pull request merged**
